# Generated by Django 4.2 on 2023-04-09 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('balance', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('invested_amount', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('open', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('turnover', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'stock_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockMetadata',
            fields=[
                ('company_name', models.CharField()),
                ('industry', models.CharField(blank=True, null=True)),
                ('symbol', models.CharField(primary_key=True, serialize=False)),
                ('isin_code', models.CharField()),
                ('price_per_share', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'stock_metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('num_shares', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('price_per_share', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('buy_or_sell', models.BooleanField()),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('name', models.CharField()),
                ('username', models.CharField(primary_key=True, serialize=False)),
                ('email', models.CharField()),
                ('password', models.CharField()),
            ],
            options={
                'db_table': 'userdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stocks.customer')),
                ('num_shares', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('invested_amount', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'portfolio',
                'managed': False,
            },
        ),
    ]
